version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: chismografo-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://roxanaort10:1234@cluster0.ejddsci.mongodb.net/chismoUTNG?retryWrites=true&w=majority&appName=Cluster0
    restart: unless-stopped
    networks:
      - chismonet

  frontend:
    build:
      context: ./frontend
    container_name: chismografo-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - chismonet

volumes:
  mongo_data:

networks:
  chismonet:
    driver: bridge
